-- 0015 — `SPEC §15` "Dropped outright": structure no rule asks for.
--
-- Four entries, three tables and one column. Every count below was measured
-- against `facet` before this file was written, and every one is zero.
--
-- **`verification_tokens` — 0 rows.** An Auth.js leftover. The claim it sat
-- under, in `schema.ts` and in `src/auth/index.ts`, was that the adapter
-- requires it. Read against `@auth/drizzle-adapter@1.11.3` that is false in
-- both halves: `verificationTokensTable` is an **optional** member of
-- `DefaultPostgresSchema` (`lib/pg.d.ts`), and the only two methods that touch
-- it — `createVerificationToken`, `useVerificationToken` — are reached solely
-- through `@auth/core`'s `signin/send-token.js`, which belongs to the Email
-- provider. The only provider configured is `Credentials`.
--
-- **`accounts` is NOT in this file, and that is the finding, not an
-- oversight.** Same table shape, same empty 0 rows, opposite answer:
-- `accountsTable` is a **non-optional** member of that type, so removing it
-- fails `npm run typecheck` with `TS2345: Property 'accountsTable' is missing
-- ... but required in type 'DefaultPostgresSchema'`. That was run, not
-- reasoned. A library that will not compile without a table is a writer, even
-- though no row is ever inserted. `users.email_verified` and `users.image`
-- stay on the identical test — `DefaultPostgresUsersTable` names both columns
-- — and both are null on all 350 users. `verify:schema25` now asserts the
-- table survives, because a regenerated migration would take it out silently:
-- login would still work, and the failure would surface as a typecheck.
--
-- **`pipeline_snapshots` — 0 rows. `person_snapshots` — 0 rows.** Written by
-- a scheduled job that was never built. `SPEC §15` hands the question to the
-- dashboard rebuild, which decides what history it needs rather than
-- inheriting a guess made before anyone had used the system. Dropping them
-- now is what stops the rebuild from being handed two tables and a shape to
-- honour. `0007` already cut `pipeline_snapshots.warmth` on the same footing —
-- "this table has never been written".
--
-- Nothing depends on any of the three: no foreign key in the database points
-- at them, checked against `pg_constraint` before generating. `DROP TABLE`
-- therefore carries no `CASCADE` — if that ever stops being true, this fails
-- loudly instead of quietly taking a dependent with it.
--
-- **`rep_reports.reference` — 0 non-null of 555 rows.** A column with no
-- writer and no reader: schema, CHECK and migration `0007` exist; the data
-- layer, the form, the screen and the message catalogue all omit it. The
-- signal reference it was modelled on is real and unaffected — that is
-- `rep_report_signals.reference`, which `S45` requires and which is written
-- and read. This was a second one, on the report itself, that nothing ever
-- filled.
--
-- Its CHECK goes with it. `rep_reports_reference` (`reference is null or
-- entry_type = 'interaction'`) is dropped by Postgres along with the only
-- column it names, so this file emits no statement for it. Verified against
-- `pg_constraint` after replay: `rep_reports` carries `rep_reports_shape` and
-- `rep_reports_on_hold` and nothing else.
--
-- CORRECTION, AUDIT 1 (§6). The sentence that stood here claimed the
-- constraint "was never declared in `schema.ts`, so drizzle-kit does not emit
-- a statement for it". Both halves are false, and it was stated as verified.
-- It IS declared in `schema.ts` — `0007` added it and the `check()` is still in
-- the `rep_reports` table definition — and it is still in
-- `meta/0015_snapshot.json`, which lists nine CHECK constraints where the
-- database has eight. Drizzle-kit emitted nothing because it compares
-- `schema.ts` against the snapshot and the two agree, not because the
-- declaration was absent.
--
-- What that leaves behind, which is the reason this correction is worth
-- writing: `schema.ts` declares a CHECK on a column that no longer exists in
-- either the file or the database. `drizzle-kit generate` compares the two
-- things that agree, so it can never surface the drift; `db:push`, which
-- compares `schema.ts` to the live database, would try to re-add the
-- constraint and fail on the missing column. The fix is one deletion in
-- `schema.ts`, and it is not this file's to make.
--
-- No rule marker moves. `SPEC §15` entries are not numbered rules, so the
-- count stays 16 CHANGE / 22 BUILD.

DROP TABLE "person_snapshots";--> statement-breakpoint
DROP TABLE "pipeline_snapshots";--> statement-breakpoint
DROP TABLE "verification_tokens";--> statement-breakpoint
ALTER TABLE "rep_reports" DROP COLUMN "reference";
