/**
 * The demo customer base — **invented lookalikes, never the real sheet.**
 *
 * This repository is private today and goes public at each audit
 * (`WORKFLOW §8`), so not one name, phone number or contact here belongs to a
 * real Technopanel customer. What is copied is the *shape* of the founder's
 * live sheet: Arabic company names with a few English ones, contractors and
 * factories dominating, Riyadh-heavy with real weight in the East, one
 * contact per company or none, and a rep's own note on roughly half.
 *
 * **Lead source is mapped, not extended** `S17`. The sheet's four values are
 * Google · Sales (Prospect) · Sales (Account) · walk-in, and `S17` fixes the
 * list at six: field visit, direct contact, referral, exhibition, marketing,
 * other. So they map —
 *
 *   Sales (Prospect) → Field visit      the rep went out and found them
 *   Sales (Account)  → Direct contact   an account already in the book
 *   walk-in          → Direct contact   they came to us
 *   Google           → Other            `S17` names no search engine, and
 *                                       Marketing means the marketing TEAM
 *                                       sourced it, which would be a lie
 *
 * — and nothing is added. A seventh lead source is a rule, not a row.
 *
 * **Marketing is absent on purpose and cannot be produced.**
 * `assertLeadSourceSelectable` admits it only for a `can_assign` holder
 * (`lookups.ts:290`), and every `can_assign` holder in `people.ts` is
 * elevated — `verify:schema25` §21 asserts that no live company membership is
 * held by one. Nobody in this dataset can both choose it and keep the company.
 *
 * **Four names are deliberately long** — two Arabic (one quiet), one
 * English, one contact.
 * `S12` gives a company a single name field, so a list's lead cell and a
 * detail heading are exactly where RTL truncation breaks, and nothing else in
 * the base is long enough to find it.
 *
 * **Reach them with `/companies?sort=recent`.** All three are recent, which
 * used to put them on page one because the list defaulted to
 * `desc(created_at)`. It defaults to attention now `D25`, and recent is the
 * calm end of that order — the long Arabic company is `age: 8`, so it sorts
 * near the *back*. That is intended, not a regression: the sort is kept
 * precisely so these stay one URL away. `verify:routes` §20 drives it.
 *
 * **The gap above closed in session 48, the other way round**: rather than
 * making a long name quiet — a clock change that would move every count the
 * suite reads — an already-quiet company (`age: 116`, last logged ~110 days
 * back in `activity.ts`) took a fourth deliberately-long Arabic name. No date moved, no group count moved,
 * and the DEFAULT attention order now carries a long name at the top of GONE
 * QUIET, where a rep actually looks (`WORKFLOW §5`).
 *
 * `region` is never written here: `S15` derives it from the city and the rep
 * is never asked. Country is Saudi unless `country` says otherwise, and a
 * non-Saudi company carries no city and no region at all `S14` `S15`.
 */

import type { PersonKey } from "./people";

/** `company_categories.name_en`. */
export type Category =
  | "Factory"
  | "Contractor"
  | "Advertising"
  | "Real Estate"
  | "Owner"
  | "Consultant"
  | "Station Management"
  | "Workshop"
  | "Personal"
  | "Other";

/** `lead_sources.name_en`, minus Marketing — see the note above. The two
 *  channels session 52 added `S17` reach four recent rows, so the
 *  *where business comes from* chart is drawn with every source a rep can
 *  pick; the pre-rule blanks (age over 45) are untouched by that. */
export type Source =
  | "Field visit"
  | "Direct contact"
  | "Referral"
  | "Exhibition"
  | "Online or WhatsApp"
  | "Consultant or architect"
  | "Other";

export type CompanyRow = {
  name: string;
  owner: PersonKey;
  category: Category;
  /** `cities.name_en`. Null only when `country` is not `SA` `S15`. */
  city: string | null;
  /** ISO 3166-1 alpha-2. Defaults to Saudi Arabia `S14`. */
  country?: string;
  source: Source;
  phone: string;
  /** Days before today the rep registered it. */
  age: number;
  /** Exactly one, or none — what the real sheet looks like `S19`. */
  contact?: { name: string; phone: string };
  /** The rep's own words — quantity, colour, and whether it is supply-only or
   *  توريد وتركيب. Roughly half carry one, as in the sheet. */
  note?: string;
};

export const COMPANIES: readonly CompanyRow[] = [
  /* ================================================================== *
   * Faisal Al-Harbi (rep-a) — Central, and the big book `D34`
   * ================================================================== */
  {
    name: "مصنع سدرة للصناعات المعدنية",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114567201",
    age: 118,
    contact: { name: "سعود المطرفي", phone: "0551204477" },
    note: "مصنع يشتري ألواح بكميات، اللون فضي ونحاسي، توريد فقط، الكمية تقريباً 480 متر",
  },
  {
    name: "شركة أنماء للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112330918",
    age: 117,
    contact: { name: "ماجد الغامدي", phone: "0503391182" },
    note: "عميل عنده واجهة مكاتب إدارية اللون نحاسي يبي توريد وتركيب، الكمية 244 متر",
  },
  {
    name: "مؤسسة الصرح الوطنية للمقاولات العامة والتشييد والصيانة والتشغيل",
    owner: "faisal",
    category: "Contractor",
    city: "Al Kharj",
    source: "Field visit",
    phone: "0115548823",
    age: 116,
  },
  {
    name: "مصنع الأفق للألمنيوم",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Referral",
    phone: "0114409911",
    age: 114,
    contact: { name: "عبدالله الشهري", phone: "0555018834" },
    note: "يطلب أبيض مطفي 4 مم، توريد فقط، الكمية 320 متر، يستلم من مخزن الرياض",
  },
  {
    name: "Delta Rock Co",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Exhibition",
    phone: "0112201477",
    age: 112,
    contact: { name: "Ziad Nassar", phone: "0566712093" },
  },
  {
    name: "مكتب المعمار الحديث للاستشارات الهندسية",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Referral",
    phone: "0112884410",
    age: 115,
    contact: { name: "م. وليد القحطاني", phone: "0509923417" },
    note: "استشاري يحدد المواصفة للمشاريع ولا يشتري بنفسه، طلب كتالوج وشهادات مقاومة الحريق",
  },
  {
    name: "شركة البناء المتين للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Field visit",
    phone: "0113376655",
    age: 109,
    contact: { name: "فهد العنزي", phone: "0554478812" },
  },
  {
    name: "مؤسسة إبداع للدعاية والإعلان",
    owner: "faisal",
    category: "Advertising",
    city: "Riyadh",
    source: "Other",
    phone: "0114998120",
    age: 108,
    note: "لوحات محلات، كميات صغيرة متكررة، أسود وأبيض، توريد وتركيب، 60 إلى 90 متر بالمرة",
  },
  {
    name: "شركة رؤى العمران للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Ad Diriyah",
    source: "Direct contact",
    phone: "0112119043",
    age: 106,
    contact: { name: "نايف السبيعي", phone: "0533320981" },
    note: "مشروع واجهة فيلا خاصة، اللون خشبي، توريد وتركيب، الكمية 210 متر",
  },
  {
    name: "مصنع نجد للكلادينج",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114771230",
    age: 104,
    contact: { name: "تركي الدوسري", phone: "0501187740" },
  },
  {
    name: "شركة تمكين للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Referral",
    phone: "0112667788",
    age: 102,
    note: "عنده مشروع برج مكاتب، رمادي داكن، توريد وتركيب، الكمية تقريباً 2,400 متر",
  },
  {
    name: "مؤسسة ركائز البناء",
    owner: "faisal",
    category: "Contractor",
    city: "Al Majma'ah",
    source: "Field visit",
    phone: "0116223390",
    age: 100,
    contact: { name: "خالد الحربي", phone: "0558840012" },
  },
  {
    name: "شركة أملاك المستقبل العقارية",
    owner: "faisal",
    category: "Real Estate",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112009911",
    age: 98,
    contact: { name: "بندر الرشيد", phone: "0505512908" },
    note: "مالك مجمع تجاري يبي تجديد الواجهة، اللون شمبين، توريد وتركيب، 640 متر",
  },
  {
    name: "مكتب أبعاد للاستشارات الهندسية",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Exhibition",
    phone: "0112447701",
    age: 96,
  },
  {
    name: "شركة الحصن للمقاولات العامة",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Field visit",
    phone: "0113998877",
    age: 95,
    contact: { name: "سلطان القرني", phone: "0567719923" },
    note: "طلب عرض سعر لواجهة مستشفى، اللون أبيض، الكمية 950 متر، توريد فقط",
  },
  {
    name: "مصنع الواحة للصناعات المعدنية",
    owner: "faisal",
    category: "Factory",
    city: "Al Kharj",
    source: "Referral",
    phone: "0115509912",
    age: 93,
  },
  {
    name: "مؤسسة سواعد التعمير",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112776540",
    age: 91,
    contact: { name: "عمر البقمي", phone: "0544410023" },
  },
  {
    name: "شركة محطات الطريق لإدارة المحطات",
    owner: "faisal",
    category: "Station Management",
    city: "Al Kharj",
    source: "Field visit",
    phone: "0115120088",
    age: 89,
    contact: { name: "مشعل العتيبي", phone: "0532218890" },
    note: "مظلات وواجهات محطتين على طريق الخرج، أحمر وأبيض، توريد وتركيب، 380 متر",
  },
  {
    name: "شركة معالم الرياض للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Referral",
    phone: "0112558833",
    age: 87,
  },
  {
    name: "مصنع الرواد للألمنيوم",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114330077",
    age: 85,
    contact: { name: "ياسر الشمري", phone: "0551129983" },
    note: "يشتري بالحاويات، أبيض وفضي 4 مم، توريد فقط، ما يحتاج تركيب أبداً",
  },
  {
    name: "شركة البنيان الراسخ للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Buraydah",
    source: "Field visit",
    phone: "0163224411",
    age: 83,
    contact: { name: "صالح المذن", phone: "0505541127" },
  },
  {
    name: "مؤسسة نبض للدعاية والإعلان",
    owner: "faisal",
    category: "Advertising",
    city: "Riyadh",
    source: "Other",
    phone: "0114112299",
    age: 81,
    note: "طلب لوحة واجهة معرض، اللون أسود مطفي، توريد وتركيب، 72 متر فقط",
  },
  {
    name: "مجموعة الفهد القابضة",
    owner: "faisal",
    category: "Owner",
    city: "Riyadh",
    source: "Referral",
    phone: "0112993311",
    age: 79,
    contact: { name: "عبدالإله الفهد", phone: "0503398821" },
  },
  {
    name: "مصنع البيان للتشكيل المعدني",
    owner: "faisal",
    category: "Factory",
    city: "Al Muzahimiyah",
    source: "Field visit",
    phone: "0115667788",
    age: 77,
    note: "مصنع صغير، يطلب دفعات 150 إلى 250 متر، اللون فضي، توريد فقط",
  },
  {
    name: "مؤسسة أساس المستقبل للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112884477",
    age: 75,
    contact: { name: "عبدالرحمن الجاسر", phone: "0556612290" },
  },
  {
    name: "مكتب الرؤية الهندسية",
    owner: "faisal",
    category: "Consultant",
    city: "Unayzah",
    source: "Exhibition",
    phone: "0163667700",
    age: 73,
  },
  {
    name: "شركة مداد العمار للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Field visit",
    phone: "0113221199",
    age: 71,
    contact: { name: "مازن الخالدي", phone: "0544478812" },
    note: "مشروع مدرسة أهلية، اللون بيج، توريد وتركيب، الكمية 410 متر",
  },
  {
    name: "مصنع تبوك الحديثة للألمنيوم",
    owner: "faisal",
    category: "Factory",
    city: "Tabuk",
    source: "Referral",
    phone: "0144229900",
    age: 69,
    contact: { name: "نواف البلوي", phone: "0507719934" },
    note: "أول تعامل، يبي عينات قبل الطلب، اللون رمادي فاتح، توريد فقط، تقريباً 260 متر",
  },
  {
    name: "مؤسسة درب الشمال للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Ha'il",
    source: "Field visit",
    phone: "0165334422",
    age: 67,
  },
  {
    name: "شركة أبراج الشمال",
    owner: "faisal",
    category: "Owner",
    city: "Tabuk",
    source: "Direct contact",
    phone: "0144117733",
    age: 65,
    contact: { name: "سالم العطوي", phone: "0533398812" },
  },
  {
    name: "شركة الفريدة للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Referral",
    phone: "0112337799",
    age: 63,
    note: "واجهة مبنى إداري، اللون نحاسي، توريد وتركيب، 288 متر",
  },
  {
    name: "مصنع الميثاق للصناعات المعدنية",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114558833",
    age: 61,
    contact: { name: "أحمد الزهراني", phone: "0551178840" },
  },
  {
    name: "مكتب خطوط التصميم للاستشارات",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Referral",
    phone: "0112229944",
    age: 59,
  },
  {
    name: "شركة نماء للتوريدات",
    owner: "faisal",
    category: "Other",
    city: "Riyadh",
    source: "Other",
    phone: "0113448899",
    age: 57,
    contact: { name: "هيثم الشريف", phone: "0509912238" },
    note: "وسيط توريد، يشتري ويبيع للمقاولين، أبيض وفضي، توريد فقط، كميات متغيرة",
  },
  {
    name: "مؤسسة واحة الوقود لإدارة المحطات",
    owner: "faisal",
    category: "Station Management",
    city: "Az Zulfi",
    source: "Field visit",
    phone: "0116441122",
    age: 55,
  },
  {
    name: "شركة الأمانة للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112118844",
    age: 53,
    contact: { name: "زياد المالكي", phone: "0555523398" },
    note: "مشروع مستودعات، اللون رمادي، توريد فقط، 520 متر",
  },
  {
    name: "مصنع الوسام للصناعات المعدنية",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114887722",
    age: 51,
  },
  {
    name: "مؤسسة بناء الوطن",
    owner: "faisal",
    category: "Contractor",
    city: "Al Kharj",
    source: "Referral",
    phone: "0115227733",
    age: 49,
    contact: { name: "فيصل الرشيدي", phone: "0533345567" },
  },
  {
    name: "شركة رسم للدعاية والإعلان",
    owner: "faisal",
    category: "Advertising",
    city: "Riyadh",
    source: "Other",
    phone: "0114339922",
    age: 47,
    note: "لوحات فروع، اللون أزرق، توريد وتركيب، 45 متر لكل فرع",
  },
  {
    name: "مكتب الزاوية للاستشارات الهندسية",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Exhibition",
    phone: "0112776622",
    age: 45,
    contact: { name: "م. طارق العمري", phone: "0501129987" },
  },
  {
    name: "شركة النهضة للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Field visit",
    phone: "0113119988",
    age: 43,
    contact: { name: "سعد الحميد", phone: "0544412209" },
    note: "برج سكني ٢٢ دور، اللون فضي لامع، توريد وتركيب، الكمية تقريباً 2,850 متر",
  },
  {
    name: "مصنع القمة للتشكيل المعدني",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Referral",
    phone: "0114226611",
    age: 41,
  },
  {
    name: "شركة قصور الرياض",
    owner: "faisal",
    category: "Owner",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112558811",
    age: 39,
    contact: { name: "عبدالعزيز الشثري", phone: "0503312298" },
    note: "مالك ثلاث فلل، اللون خشبي، توريد وتركيب، 180 متر لكل فيلا",
  },
  {
    name: "مؤسسة الشرق للتجارة العامة",
    owner: "faisal",
    category: "Other",
    city: "Riyadh",
    source: "Other",
    phone: "0113667744",
    age: 37,
  },
  {
    name: "شركة سواري للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Ad Diriyah",
    source: "Field visit",
    phone: "0112994411",
    age: 35,
    contact: { name: "منصور الدايل", phone: "0556678823" },
  },
  {
    name: "مصنع المدى للألمنيوم",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114558811",
    age: 33,
    note: "طلب دائم كل شهرين، اللون فضي، توريد فقط، 300 متر بالطلب",
  },
  {
    name: "مؤسسة الخطوة الأولى للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112337744",
    age: 31,
  },
  {
    name: "مكتب البعد الثالث للاستشارات",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Referral",
    phone: "0112889933",
    age: 29,
    contact: { name: "م. ريان الشمراني", phone: "0509987712" },
  },
  {
    name: "شركة الياقوت للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Buraydah",
    source: "Field visit",
    phone: "0163889911",
    age: 27,
    contact: { name: "بدر السحيباني", phone: "0533312290" },
    note: "واجهة معرض سيارات، اللون أسود مطفي، توريد وتركيب، 320 متر",
  },
  {
    name: "مؤسسة المدار للدعاية والإعلان",
    owner: "faisal",
    category: "Advertising",
    city: "Riyadh",
    source: "Other",
    phone: "0114117733",
    age: 25,
  },
  {
    name: "مصنع الرياض للأبواب والنوافذ",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114669922",
    age: 23,
    contact: { name: "وليد الجهني", phone: "0551123398" },
    note: "يشتري للأبواب فقط، ألواح 3 مم، اللون بني، توريد فقط، 165 متر",
  },
  {
    name: "شركة الميدان للاستثمار",
    owner: "faisal",
    category: "Owner",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112447799",
    age: 21,
  },
  {
    name: "مؤسسة إتقان التعمير",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Referral",
    phone: "0113558822",
    age: 19,
    contact: { name: "عادل القثامي", phone: "0544456678" },
  },
  {
    name: "ورشة الإتقان للتشكيل المعدني",
    owner: "faisal",
    category: "Workshop",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114772211",
    age: 17,
    note: "ورشة صغيرة، تشتري بواقي وكميات صغيرة، اللون حسب المتوفر، توريد فقط",
  },
  {
    name: "شركة الرافدين للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0112119977",
    age: 15,
    contact: { name: "إياد الحسن", phone: "0505578834" },
  },
  {
    name: "فهد بن عبدالله العتيبي",
    owner: "faisal",
    category: "Personal",
    city: "Riyadh",
    source: "Other",
    phone: "0553341129",
    age: 13,
    note: "زبون شخصي، واجهة استراحة، اللون خشبي، توريد وتركيب، 95 متر",
  },
  {
    name: "مؤسسة الاستراحة لإدارة المحطات",
    owner: "faisal",
    category: "Station Management",
    city: "Al Kharj",
    source: "Field visit",
    phone: "0115889933",
    age: 11,
    contact: { name: "حمد الدوسري", phone: "0533398845" },
  },
  {
    name: "شركة ناصر بن عبدالله الحقباني للاستثمار والتطوير العقاري",
    owner: "faisal",
    category: "Real Estate",
    city: "Riyadh",
    source: "Referral",
    phone: "0112006677",
    age: 8,
    contact: { name: "م. عبدالمحسن بن عبدالرحمن الخريّجي", phone: "0503398877" },
    note: "مطور عقاري، ثلاثة مشاريع سكنية دفعة واحدة، اللون رمادي وخشبي، توريد وتركيب، الكمية الإجمالية تقارب 3,100 متر",
  },
  {
    name: "مصنع الشعلة للألمنيوم",
    owner: "faisal",
    category: "Factory",
    city: "Riyadh",
    source: "Field visit",
    phone: "0114003322",
    age: 6,
    contact: { name: "راكان العمري", phone: "0551167789" },
  },
  {
    name: "شركة واجهات المملكة للمقاولات",
    owner: "faisal",
    category: "Contractor",
    city: "Riyadh",
    source: "Online or WhatsApp",
    phone: "0112889911",
    age: 4,
    contact: { name: "أنس الشهراني", phone: "0544490012" },
    note: "مشروع فندق، اللون شمبين، توريد وتركيب، الكمية 1,150 متر",
  },
  {
    name: "مكتب الميزان الهندسي",
    owner: "faisal",
    category: "Consultant",
    city: "Riyadh",
    source: "Consultant or architect",
    phone: "0112337766",
    age: 2,
  },

  /* ================================================================== *
   * Saad Al-Qahtani (rep-b) — the East
   * ================================================================== */
  {
    name: "مصنع درة الشرق للصناعة",
    owner: "saad",
    category: "Factory",
    city: "Dammam",
    source: "Field visit",
    phone: "0138221199",
    age: 119,
    contact: { name: "علي الشيخ", phone: "0503398812" },
    note: "مصنع كبير، طلبات شهرية، أبيض وفضي 4 مم، توريد فقط، 600 متر بالطلب",
  },
  {
    name: "شركة بوابة الشرق للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Jubail",
    source: "Direct contact",
    phone: "0133447722",
    age: 115,
    contact: { name: "حسين البقشي", phone: "0555512234" },
  },
  {
    name: "مصنع الخليج الأول للألمنيوم",
    owner: "saad",
    category: "Factory",
    city: "Al Khobar",
    source: "Referral",
    phone: "0138990011",
    age: 110,
    note: "يطلب ألواح مقاومة حريق A2، اللون رمادي، توريد فقط، 450 متر",
  },
  {
    name: "شركة مرافئ الدمام للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Dammam",
    source: "Field visit",
    phone: "0138334455",
    age: 105,
    contact: { name: "ماجد آل سعيد", phone: "0533345512" },
    note: "مشروع مبنى إداري بالميناء، اللون أزرق داكن، توريد وتركيب، 780 متر",
  },
  {
    name: "شركة أعمدة الخليج للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Jubail",
    source: "Direct contact",
    phone: "0133228877",
    age: 99,
  },
  {
    name: "مؤسسة معمار الشرق",
    owner: "saad",
    category: "Contractor",
    city: "Dhahran",
    source: "Referral",
    phone: "0138445566",
    age: 94,
    contact: { name: "عمار الجشي", phone: "0509912234" },
  },
  {
    name: "مؤسسة ألوان الشرق للدعاية والإعلان",
    owner: "saad",
    category: "Advertising",
    city: "Al Khobar",
    source: "Other",
    phone: "0138112233",
    age: 90,
    note: "لوحات مطاعم، ألوان متعددة، توريد وتركيب، 55 متر بالطلب",
  },
  {
    name: "مصنع صدف للصناعات المعدنية",
    owner: "saad",
    category: "Factory",
    city: "Qatif",
    source: "Field visit",
    phone: "0138556677",
    age: 86,
  },
  {
    name: "شركة الربيع للمقاولات العامة",
    owner: "saad",
    category: "Contractor",
    city: "Hofuf",
    source: "Field visit",
    phone: "0135889900",
    age: 82,
    contact: { name: "عبدالله الهاجري", phone: "0551123345" },
    note: "مشروع مدارس، اللون بيج، توريد وتركيب، 940 متر على ثلاث مراحل",
  },
  {
    name: "مصنع الفرات للألمنيوم",
    owner: "saad",
    category: "Factory",
    city: null,
    country: "SY",
    source: "Referral",
    phone: "0966114455",
    age: 78,
    contact: { name: "سامر الحلبي", phone: "0966332211" },
    note: "عميل خارج المملكة، الشحن على حسابه، اللون فضي، توريد فقط، 300 متر",
  },
  {
    name: "مكتب المحور للاستشارات الهندسية",
    owner: "saad",
    category: "Consultant",
    city: "Al Khobar",
    source: "Exhibition",
    phone: "0138667788",
    age: 74,
  },
  {
    name: "شركة مسار لإدارة المحطات",
    owner: "saad",
    category: "Station Management",
    city: "Dammam",
    source: "Field visit",
    phone: "0138990022",
    age: 70,
    contact: { name: "فواز العجمي", phone: "0533312278" },
    note: "خمس محطات على طريق الجبيل، أحمر وأبيض، توريد وتركيب، 210 متر للمحطة",
  },
  {
    name: "مجموعة الوادي التجارية",
    owner: "saad",
    category: "Owner",
    city: "Dammam",
    source: "Direct contact",
    phone: "0138223344",
    age: 66,
  },
  {
    name: "مصنع الساحل للألمنيوم",
    owner: "saad",
    category: "Factory",
    city: "Ras Tanura",
    source: "Field visit",
    phone: "0136778899",
    age: 62,
    contact: { name: "طلال الدوسري", phone: "0505523389" },
  },
  {
    name: "شركة الشاطئ الأزرق للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Al Khobar",
    source: "Referral",
    phone: "0138334477",
    age: 58,
    contact: { name: "عبدالمجيد آل فهد", phone: "0544478890" },
    note: "أبراج سكنية على الكورنيش، اللون فضي لامع، توريد وتركيب، 2,150 متر",
  },
  {
    name: "مؤسسة الضوء للدعاية والإعلان",
    owner: "saad",
    category: "Advertising",
    city: "Dammam",
    source: "Other",
    phone: "0138441122",
    age: 54,
  },
  {
    name: "مصنع النخبة للتشكيل المعدني",
    owner: "saad",
    category: "Factory",
    city: "Al Mubarraz",
    source: "Field visit",
    phone: "0135667788",
    age: 50,
    note: "مصنع متوسط، يطلب 200 إلى 350 متر، اللون أبيض، توريد فقط",
  },
  {
    name: "شركة السد للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Hofuf",
    source: "Direct contact",
    phone: "0135223344",
    age: 46,
    contact: { name: "ناصر المهنا", phone: "0551178823" },
  },
  {
    name: "مكتب صياغة للاستشارات الهندسية",
    owner: "saad",
    category: "Consultant",
    city: "Dammam",
    source: "Referral",
    phone: "0138778811",
    age: 42,
  },
  {
    name: "Silver Line Contracting",
    owner: "saad",
    category: "Contractor",
    city: "Al Khobar",
    source: "Exhibition",
    phone: "0138009911",
    age: 38,
    contact: { name: "Rami Haddad", phone: "0566623390" },
    note: "مشروع مركز تجاري، اللون نحاسي، توريد وتركيب، 1,320 متر",
  },
  {
    name: "مؤسسة حصاد البناء",
    owner: "saad",
    category: "Contractor",
    city: "Jubail",
    source: "Field visit",
    phone: "0133667799",
    age: 34,
  },
  {
    name: "مصنع الجزيرة للواجهات",
    owner: "saad",
    category: "Factory",
    city: "Dammam",
    source: "Field visit",
    phone: "0138556644",
    age: 30,
    contact: { name: "خالد العوامي", phone: "0533367712" },
  },
  {
    name: "مجموعة الرمال القابضة",
    owner: "saad",
    category: "Owner",
    city: "Al Khobar",
    source: "Direct contact",
    phone: "0138112277",
    age: 26,
    note: "مالك مبنى مكاتب قديم، يبي تجديد كامل، اللون رمادي، توريد وتركيب، 690 متر",
  },
  {
    name: "شركة نقاط الخدمة لإدارة المحطات",
    owner: "saad",
    category: "Station Management",
    city: "Hofuf",
    source: "Field visit",
    phone: "0135334422",
    age: 22,
  },
  {
    name: "مؤسسة الإشارة للدعاية والإعلان",
    owner: "saad",
    category: "Advertising",
    city: "Dammam",
    source: "Other",
    phone: "0138224466",
    age: 18,
    contact: { name: "يوسف الخباز", phone: "0509923312" },
  },
  {
    name: "شركة الرافد للمقاولات",
    owner: "saad",
    category: "Contractor",
    city: "Dammam",
    source: "Referral",
    phone: "0138337799",
    age: 12,
    contact: { name: "مهند السبيعي", phone: "0544423398" },
    note: "مشروع مستشفى خاص، اللون أبيض، توريد وتركيب، 1,480 متر",
  },
  {
    name: "Northern Gulf General Trading and Contracting Establishment",
    owner: "saad",
    category: "Other",
    city: "Jubail",
    source: "Online or WhatsApp",
    phone: "0133889900",
    age: 5,
    contact: { name: "Abdulwahab Al-Munajjem", phone: "0566645512" },
    note: "وسيط توريد للمقاولين في الجبيل، ألوان متعددة، توريد فقط، الكميات متغيرة",
  },

  /* ================================================================== *
   * Majed Al-Dosari (rep-c) — the West
   * ================================================================== */
  {
    name: "شركة صروح جدة للمقاولات",
    owner: "majed",
    category: "Contractor",
    city: "Jeddah",
    source: "Field visit",
    phone: "0126778899",
    age: 113,
    contact: { name: "أيمن باشراحيل", phone: "0555523312" },
    note: "برج مكاتب على طريق المدينة، اللون رمادي داكن، توريد وتركيب، 2,600 متر",
  },
  {
    name: "مصنع البحر الأحمر للألمنيوم",
    owner: "majed",
    category: "Factory",
    city: "Jeddah",
    source: "Referral",
    phone: "0126334455",
    age: 111,
    contact: { name: "سمير الحربي", phone: "0503312245" },
  },
  {
    name: "شركة تلال جدة للمقاولات",
    owner: "majed",
    category: "Contractor",
    city: "Jeddah",
    source: "Direct contact",
    phone: "0126112233",
    age: 101,
    note: "مجمع سكني، اللون خشبي وأبيض، توريد وتركيب، 1,050 متر",
  },
  {
    name: "unico aluminum factory",
    owner: "majed",
    category: "Factory",
    city: "Jeddah",
    source: "Exhibition",
    phone: "0126889900",
    age: 97,
    contact: { name: "Nabil Zahran", phone: "0566612278" },
    note: "مصنع، يشتري بالحاويات، فضي وأبيض 4 مم، توريد فقط، 700 متر",
  },
  {
    name: "مؤسسة الأفنان للتجارة",
    owner: "majed",
    category: "Other",
    city: "Madinah",
    source: "Other",
    phone: "0148223344",
    age: 92,
  },
  {
    name: "شركة مراسي جدة",
    owner: "majed",
    category: "Owner",
    city: "Jeddah",
    source: "Direct contact",
    phone: "0126445566",
    age: 84,
    contact: { name: "عبدالله باعشن", phone: "0533312267" },
    note: "مالك فندق على الكورنيش، اللون شمبين، توريد وتركيب، 1,900 متر",
  },
  {
    name: "مكتب الأثر للاستشارات الهندسية",
    owner: "majed",
    category: "Consultant",
    city: "Jeddah",
    source: "Referral",
    phone: "0126556677",
    age: 76,
  },
  {
    name: "مصنع الأصالة للألمنيوم",
    owner: "majed",
    category: "Factory",
    city: "Madinah",
    source: "Field visit",
    phone: "0148334455",
    age: 68,
    contact: { name: "ماهر الجهني", phone: "0551123312" },
  },
  {
    name: "شركة واجهة للدعاية والإعلان",
    owner: "majed",
    category: "Advertising",
    city: "Jeddah",
    source: "Other",
    phone: "0126667788",
    age: 60,
    note: "لوحات مراكز تجارية، اللون أسود، توريد وتركيب، 120 متر",
  },
  {
    name: "Prime Facade Systems",
    owner: "majed",
    category: "Contractor",
    city: "Jeddah",
    source: "Exhibition",
    phone: "0126990011",
    age: 52,
    contact: { name: "Karim Fouad", phone: "0509987723" },
  },
  {
    name: "مصنع الينابيع للصناعات المعدنية",
    owner: "majed",
    category: "Factory",
    city: "Yanbu",
    source: "Field visit",
    phone: "0143445566",
    age: 44,
    contact: { name: "بسام الرفاعي", phone: "0544412234" },
    note: "طلب أول مرة، اللون رمادي فاتح، توريد فقط، 240 متر",
  },
  {
    name: "شركة دار الوفاء للتطوير",
    owner: "majed",
    category: "Owner",
    city: "Ta'if",
    source: "Direct contact",
    phone: "0127556677",
    age: 36,
  },
  {
    name: "مصنع القاهرة للألمنيوم",
    owner: "majed",
    category: "Factory",
    city: null,
    country: "EG",
    source: "Referral",
    phone: "0202445566",
    age: 24,
    contact: { name: "مصطفى عبدالحميد", phone: "0201122334" },
    note: "عميل مصري، يستلم من ميناء جدة، اللون أبيض، توريد فقط، 380 متر",
  },
  {
    name: "شركة مرافئ العقارية",
    owner: "majed",
    category: "Real Estate",
    city: "Jeddah",
    source: "Consultant or architect",
    phone: "0126223344",
    age: 9,
    contact: { name: "طلال بازرعة", phone: "0555567712" },
    note: "مشروع أبراج، اللون فضي، توريد وتركيب، 2,400 متر، ينتظر اعتماد التصميم",
  },

  /* ================================================================== *
   * Turki Al-Shammari (rep-d) — the South, and the smallest book `D34`
   * ================================================================== */
  {
    name: "شركة ديار الجنوب للمقاولات",
    owner: "turki",
    category: "Contractor",
    city: "Abha",
    source: "Field visit",
    phone: "0172334455",
    age: 103,
    contact: { name: "سعيد آل مانع", phone: "0533398834" },
    note: "مشروع مبنى بلدية، اللون بيج، توريد وتركيب، 520 متر",
  },
  {
    name: "مصنع تهامة للألمنيوم",
    owner: "turki",
    category: "Factory",
    city: "Jazan",
    source: "Referral",
    phone: "0173445566",
    age: 88,
    contact: { name: "حسن المالكي", phone: "0551167712" },
  },
  {
    name: "شركة عسير للتعمير والمقاولات",
    owner: "turki",
    category: "Contractor",
    city: "Khamis Mushait",
    source: "Field visit",
    phone: "0172556677",
    age: 80,
    note: "واجهة مركز صحي، اللون أبيض، توريد وتركيب، 290 متر",
  },
  {
    name: "مصنع بوابة نجران للصناعة",
    owner: "turki",
    category: "Factory",
    city: "Najran",
    source: "Direct contact",
    phone: "0175667788",
    age: 72,
  },
  {
    name: "مؤسسة الطريق السريع لإدارة المحطات",
    owner: "turki",
    category: "Station Management",
    city: "Bisha",
    source: "Field visit",
    phone: "0176778899",
    age: 64,
    contact: { name: "مفرح الشهري", phone: "0505578812" },
    note: "محطة على طريق بيشة، أحمر وأبيض، توريد وتركيب، 175 متر",
  },
  {
    name: "مصنع الشروق للتشكيل المعدني",
    owner: "turki",
    category: "Factory",
    city: "Abha",
    source: "Referral",
    phone: "0172889900",
    age: 56,
  },
  {
    name: "شركة الياسمين للمقاولات",
    owner: "turki",
    category: "Contractor",
    city: "Jazan",
    source: "Field visit",
    phone: "0173112233",
    age: 48,
    contact: { name: "أحمد حكمي", phone: "0544456612" },
    note: "مشروع كورنيش جازان، اللون أزرق، توريد وتركيب، 640 متر",
  },
  {
    name: "مكتب الرصانة للاستشارات الهندسية",
    owner: "turki",
    category: "Consultant",
    city: "Khamis Mushait",
    source: "Exhibition",
    phone: "0172223344",
    age: 40,
  },
  {
    name: "مؤسسة النقش للدعاية والإعلان",
    owner: "turki",
    category: "Advertising",
    city: "Abha",
    source: "Other",
    phone: "0172445599",
    age: 32,
    contact: { name: "عوض القحطاني", phone: "0533345523" },
  },
  {
    name: "مصنع المنارة للألمنيوم",
    owner: "turki",
    category: "Factory",
    city: "Sabya",
    source: "Field visit",
    phone: "0173556688",
    age: 28,
    note: "مصنع صغير، يطلب 150 إلى 200 متر، اللون فضي، توريد فقط",
  },
  {
    name: "مؤسسة السحاب للاستثمار",
    owner: "turki",
    category: "Owner",
    city: "Abha",
    source: "Direct contact",
    phone: "0172667711",
    age: 20,
    contact: { name: "مسفر آل سعد", phone: "0509912256" },
  },
  {
    name: "شركة جبال السروات للمقاولات",
    owner: "turki",
    category: "Contractor",
    city: "Abha",
    source: "Referral",
    phone: "0172778822",
    age: 16,
    contact: { name: "فايز عسيري", phone: "0551145578" },
    note: "منتجع جبلي، اللون خشبي، توريد وتركيب، 830 متر",
  },
  {
    name: "Bright Sign Est",
    owner: "turki",
    category: "Advertising",
    city: "Najran",
    source: "Exhibition",
    phone: "0175889911",
    age: 10,
  },
  {
    name: "مؤسسة بيت الخير للاستثمار",
    owner: "turki",
    category: "Owner",
    city: "Jazan",
    source: "Direct contact",
    phone: "0173667722",
    age: 7,
    contact: { name: "إبراهيم مدخلي", phone: "0544478856" },
  },
  {
    name: "مصنع الهدى للصناعات المعدنية",
    owner: "turki",
    category: "Factory",
    city: "Khamis Mushait",
    source: "Field visit",
    phone: "0172889933",
    age: 3,
    note: "مصنع جديد، طلب عينات أولاً، اللون رمادي، توريد فقط، 220 متر",
  },

  /* ================================================================== *
   * Nouf Al-Mutairi (coordinator) — she holds a book like any rep
   * `S9`, and may raise and approve against it `S127`
   * ================================================================== */
  {
    name: "شركة لمسات للدعاية والإعلان",
    owner: "nouf",
    category: "Advertising",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0114226699",
    age: 96,
    contact: { name: "دانة العلي", phone: "0555534412" },
    note: "عميلة قديمة تتعامل مع المكتب مباشرة، لوحات، اللون أبيض، توريد وتركيب، 80 متر",
  },
  {
    name: "مصنع جسور للصناعات المعدنية",
    owner: "nouf",
    category: "Factory",
    city: "Riyadh",
    source: "Referral",
    phone: "0114337722",
    age: 68,
    contact: { name: "عبدالسلام الفضل", phone: "0503345567" },
  },
  {
    name: "Harbour Square",
    owner: "nouf",
    category: "Other",
    city: null,
    country: "AE",
    source: "Exhibition",
    phone: "0971442233",
    age: 44,
    contact: { name: "Tarek Sabbagh", phone: "0971552211" },
    note: "عميل من الإمارات، الشحن كارجو على حسابه، اللون فضي، توريد فقط، 410 متر",
  },
  {
    name: "شركة المحترف للدعاية والإعلان",
    owner: "nouf",
    category: "Advertising",
    city: "Riyadh",
    source: "Direct contact",
    phone: "0114448833",
    age: 14,
  },
] as const;
