"use server";

import { getLocale } from "next-intl/server";
import { revalidatePath } from "next/cache";

import { redirect } from "@/i18n/navigation";
import { requireSession } from "@/lib/authz";
import { recordDispatch, type DispatchLineInput } from "@/lib/dispatches";
import { readFields, ruleErrorState, type FormState } from "@/lib/validation";

import { readProductLine } from "../quotations/line-form";

/** How many repeated line rows the form may send. The screen adds them one at
 *  a time, so this only bounds a hand-made POST. */
const MAX_LINES = 40;

/**
 * Every action calls `requireSession()` itself. A server action is a
 * separately reachable POST endpoint; no layout wraps it, so the gate cannot
 * be inherited. `recordDispatch` then re-checks `can_dispatch`, the payment
 * gate `[07 C3]`, the issued-version gate `S126`, the company lookup
 * `[18 §2]` and every line's price `S116` before it writes — this function
 * only shapes the input.
 */
export async function recordDispatchAction(
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);

  // The two entry points of `07 C6`, which carry `S75`'s three routes: against
  // a quotation the lines arrive prefilled and are kept or edited — the first
  // two routes, indistinguishable here on purpose — and a free entry types
  // them from nothing. Company and rep are DERIVED from the thread `[18 §7]`
  // and the form does not offer them; a free entry must name both.
  const quotationThreadId = fields.uuid("quotationThreadId");
  const isDirect = !quotationThreadId;

  const companyId = isDirect
    ? fields.uuid("companyId", { required: true })
    : null;
  const userId = isDirect ? fields.uuid("userId", { required: true }) : null;
  // `S74` — shape only. Whether it is required, ignored or refused depends on
  // the quotation's own project, which only the data layer can read.
  const projectId = isDirect ? null : fields.uuid("projectId");
  const dispatchDate = fields.date("dispatchDate", { required: true });

  // `S116` — the lines, read with the quotation form's own reader and
  // `priceRequired`, which is the one thing that differs `S58`. **No `sqm`
  // field is read, because the form no longer offers one**: a dispatch's
  // square metres are its lines', generated by the database.
  const lines: DispatchLineInput[] = [];
  const rowCount = Math.min(formData.getAll("supplierId").length, MAX_LINES);
  for (let index = 0; index < rowCount; index += 1) {
    const line = readProductLine(fields, index, formData, {
      priceRequired: true,
    });
    if (!line) continue; // an untouched spare row
    if (!line.customColour) fields.fail("customColour", "validation.required");
    lines.push({
      supplierId: line.supplierId,
      classId: line.classId,
      fireRatingId: line.fireRatingId,
      customColour: line.customColour ?? "",
      thicknessId: line.thicknessId,
      widthM: line.widthM,
      lengthM: line.lengthM,
      quantityPcs: line.quantityPcs,
      unitPrice: line.unitPrice ?? "",
    });
  }
  // A form with no filled row at all. The data layer refuses it too, with the
  // same key — this only spares a round trip.
  if (lines.length === 0) fields.fail("supplierId", "validation.required");

  if (!fields.ok || !dispatchDate) return fields.state;

  let dispatchId: string;
  try {
    const dispatch = await recordDispatch(session, {
      lines,
      dispatchDate,
      quotationThreadId,
      companyId,
      userId,
      projectId,
    });
    dispatchId = dispatch.id;
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }

  const locale = await getLocale();
  revalidatePath("/dispatches");
  revalidatePath("/targets");
  // `S74` — dispatching can write a project onto a quotation and add a
  // participant to that project, so both of those screens are now stale.
  revalidatePath("/quotations");
  revalidatePath("/projects");
  redirect({ href: `/dispatches/${dispatchId}`, locale });
  throw new Error("unreachable"); // redirect() never returns
}
