"use server";

import { getLocale } from "next-intl/server";
import { revalidatePath } from "next/cache";

import { redirect } from "@/i18n/navigation";
import { requireSession } from "@/lib/authz";
import {
  approveDispatchRequest,
  refuseDispatchRequest,
  requestDispatch,
  reviveDispatchRequest,
  submitDispatchRequest,
  updateDispatchRequest,
  type DispatchLineInput,
} from "@/lib/dispatches";
import { COMMENT_BODY_MAX } from "@/lib/enums";
import { readFields, ruleErrorState, type FormState } from "@/lib/validation";

import { readProductLine } from "../quotations/line-form";

/** How many repeated line rows a form may send. The screen adds them one at a
 *  time, so this only bounds a hand-made POST. */
const MAX_LINES = 40;

/**
 * The six acts of `S72`, one action each.
 *
 * **Every action calls `requireSession()` itself.** A server action is a
 * separately reachable POST endpoint; no layout wraps it, so the gate cannot be
 * inherited — and since `S72` that matters more than it did, because
 * `/dispatches/new` no longer has a `can_dispatch` gate to inherit anyway. The
 * data layer re-checks every rule before it writes `S109`; these functions only
 * shape the input.
 *
 * **What each one revalidates** is what its act can change, and only approval
 * changes a figure. `/dispatches` always; `/targets`, `/quotations` and
 * `/projects` on approval alone — approval is what credits `S72`, and it is
 * where `S74`'s write-back fires and can add a participant. Requesting,
 * editing, submitting, refusing and reviving move no square metres anywhere,
 * which is the whole of `S72` seen from the cache.
 */

/** The lines, read with the quotation form's own reader and `priceRequired`,
 *  which is the one thing that differs `S58` `S116`. No `sqm` field is read: a
 *  dispatch's square metres are its lines', generated by the database. */
function readLines(formData: FormData, fields: ReturnType<typeof readFields>) {
  const lines: DispatchLineInput[] = [];
  const rowCount = Math.min(formData.getAll("supplierId").length, MAX_LINES);
  for (let index = 0; index < rowCount; index += 1) {
    const line = readProductLine(fields, index, formData, {
      priceRequired: true,
    });
    if (!line) continue; // an untouched spare row
    if (!line.customColour) fields.fail("customColour", "validation.required");
    lines.push({
      supplierId: line.supplierId,
      classId: line.classId,
      fireRatingId: line.fireRatingId,
      customColour: line.customColour ?? "",
      thicknessId: line.thicknessId,
      widthM: line.widthM,
      lengthM: line.lengthM,
      quantityPcs: line.quantityPcs,
      unitPrice: line.unitPrice ?? "",
    });
  }
  // A form with no filled row at all. The data layer refuses it too, with the
  // same key — this only spares a round trip.
  if (lines.length === 0) fields.fail("supplierId", "validation.required");
  return lines;
}

/**
 * **A rep raises a request** `S72`. No permission check of its own, here or in
 * the data layer — that is the whole of the rule.
 */
export async function requestDispatchAction(
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);

  // The two entry points of `07 C6`, carrying `S75`'s three routes: against a
  // quotation the lines arrive prefilled and are kept or edited — the first two
  // routes, indistinguishable here on purpose — and a free entry types them.
  // Company and rep are DERIVED from the thread `[18 §7]` and the form does not
  // offer them; a free entry names a company, and names a rep only when a
  // `can_dispatch` holder is raising one for somebody else `S108`.
  const quotationThreadId = fields.uuid("quotationThreadId");
  const isFreeEntry = !quotationThreadId;

  const companyId = isFreeEntry
    ? fields.uuid("companyId", { required: true })
    : null;
  const userId = isFreeEntry ? fields.uuid("userId") : null;
  // `S74` — shape only. Whether it is required, ignored or refused depends on
  // the quotation's own project, which only the data layer can read.
  const projectId = isFreeEntry ? null : fields.uuid("projectId");
  const dispatchDate = fields.date("dispatchDate", { required: true });

  const lines = readLines(formData, fields);
  if (!fields.ok || !dispatchDate) return fields.state;

  let dispatchId: string;
  try {
    const dispatch = await requestDispatch(session, {
      lines,
      dispatchDate,
      quotationThreadId,
      companyId,
      userId,
      projectId,
    });
    dispatchId = dispatch.id;
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }

  const locale = await getLocale();
  revalidatePath("/dispatches");
  redirect({ href: `/dispatches/${dispatchId}`, locale });
  throw new Error("unreachable"); // redirect() never returns
}

/**
 * **Edit a request** `S125` `S62` — the rep's while it is a draft, the
 * coordinator's once it is submitted. Which of the two is asking is the data
 * layer's question, not this one's.
 */
export async function updateDispatchRequestAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);

  const projectId = fields.uuid("projectId");
  const dispatchDate = fields.date("dispatchDate", { required: true });
  const lines = readLines(formData, fields);
  if (!fields.ok || !dispatchDate) return fields.state;

  try {
    await updateDispatchRequest(session, id, { lines, dispatchDate, projectId });
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }

  const locale = await getLocale();
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  redirect({ href: `/dispatches/${id}`, locale });
  throw new Error("unreachable"); // redirect() never returns
}

/** **The rep hands it over** `S72`. */
export async function submitDispatchRequestAction(
  id: string,
): Promise<FormState> {
  const session = await requireSession();
  try {
    await submitDispatchRequest(session, id);
  } catch (error) {
    return ruleErrorState(error);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}

/**
 * **The coordinator approves** `S72` — the one event that credits a target, and
 * the one that fires `S74`'s write-back. Four screens go stale at once.
 */
export async function approveDispatchRequestAction(
  id: string,
): Promise<FormState> {
  const session = await requireSession();
  try {
    await approveDispatchRequest(session, id);
  } catch (error) {
    return ruleErrorState(error);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  // Approval is what credits `S72`, so the achievement figures are stale.
  revalidatePath("/targets");
  // `S74` — approving can write a project onto a quotation and add a
  // participant to that project, so both of those screens are stale too.
  revalidatePath("/quotations");
  revalidatePath("/projects");
  return {};
}

/** **The coordinator refuses**, with a reason `S124`, which archives it `S122`. */
export async function refuseDispatchRequestAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);
  const reason = fields.text("reason", {
    required: true,
    max: COMMENT_BODY_MAX,
  });
  if (!fields.ok || !reason) return fields.state;

  try {
    await refuseDispatchRequest(session, id, reason);
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}

/** **Only the coordinator may revive one** `S122`, and it returns to the rep. */
export async function reviveDispatchRequestAction(
  id: string,
): Promise<FormState> {
  const session = await requireSession();
  try {
    await reviveDispatchRequest(session, id);
  } catch (error) {
    return ruleErrorState(error);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}
