"use server";

import { getLocale } from "next-intl/server";
import { revalidatePath } from "next/cache";

import { redirect } from "@/i18n/navigation";
import { requireSession } from "@/lib/authz";
import {
  approveDispatchRequest,
  refuseDispatchRequest,
  requestDispatch,
  reviveDispatchRequest,
  setDispatchSmacNumber,
  submitDispatchRequest,
  updateDispatchRequest,
  type DispatchLineInput,
} from "@/lib/dispatches";
import {
  COMMENT_BODY_MAX,
  PAYMENT_METHODS,
  SHIPMENT_METHODS,
  STOCKS,
} from "@/lib/enums";
import { readFields, ruleErrorState, type FormState } from "@/lib/validation";

import { readProductLine } from "../quotations/line-form";

/** How many repeated line rows a form may send. The screen adds them one at a
 *  time, so this only bounds a hand-made POST. */
const MAX_LINES = 40;

/**
 * The six acts of `S72`, one action each.
 *
 * **Every action calls `requireSession()` itself.** A server action is a
 * separately reachable POST endpoint; no layout wraps it, so the gate cannot be
 * inherited — and since `S72` that matters more than it did, because
 * `/dispatches/new` no longer has a `can_dispatch` gate to inherit anyway. The
 * data layer re-checks every rule before it writes `S109`; these functions only
 * shape the input.
 *
 * **What each one revalidates** is what its act can change, and only approval
 * changes a figure. `/dispatches` always; `/targets`, `/quotations` and
 * `/projects` on approval alone — approval is what credits `S72`, and it is
 * where `S74`'s write-back fires and can add a participant. Requesting,
 * editing, submitting, refusing and reviving move no square metres anywhere,
 * which is the whole of `S72` seen from the cache.
 */

/** The lines, read with the quotation form's own reader and `priceRequired`,
 *  which is the one thing that differs `S58` `S116`. No `sqm` field is read: a
 *  dispatch's square metres are its lines', generated by the database. */
function readLines(formData: FormData, fields: ReturnType<typeof readFields>) {
  const lines: DispatchLineInput[] = [];
  const rowCount = Math.min(formData.getAll("supplierId").length, MAX_LINES);
  for (let index = 0; index < rowCount; index += 1) {
    const line = readProductLine(fields, index, formData, {
      priceRequired: true,
    });
    if (!line) continue; // an untouched spare row
    if (!line.customColour) fields.fail("customColour", "validation.required");
    lines.push({
      supplierId: line.supplierId,
      classId: line.classId,
      fireRatingId: line.fireRatingId,
      customColour: line.customColour ?? "",
      thicknessId: line.thicknessId,
      widthM: line.widthM,
      lengthM: line.lengthM,
      quantityPcs: line.quantityPcs,
      unitPrice: line.unitPrice ?? "",
    });
  }
  // A form with no filled row at all. The data layer refuses it too, with the
  // same key — this only spares a round trip.
  if (lines.length === 0) fields.fail("supplierId", "validation.required");
  return lines;
}

/**
 * The three fields `S130` and `S119` put on a request, read the same way by
 * both forms so the raise and the edit cannot disagree about their shape.
 *
 * Shape only. That South and Dammam force CT, and that a destination belongs
 * to Cargo alone, are `assertShipment`'s in the data layer and two CHECKs at
 * the database — neither is a thing a form reader can answer, because both
 * compare two fields rather than validating one.
 */
function readShipment(fields: ReturnType<typeof readFields>) {
  return {
    stock: fields.option("stock", STOCKS, { required: true }),
    shipment: fields.option("shipment", SHIPMENT_METHODS, { required: true }),
    // `S119` — optional. Read on every shipment, never silently dropped on the
    // ones that may not carry it: the data layer refuses it against the field
    // instead, because an input that vanishes is `AUDIT 1 F3`'s defect.
    cargoDestination: fields.text("cargoDestination", { max: 200 }),
  };
}

/**
 * **A rep raises a request** `S72`. No permission check of its own, here or in
 * the data layer — that is the whole of the rule.
 */
export async function requestDispatchAction(
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);

  // The two entry points of `07 C6`, carrying `S75`'s three routes: against a
  // quotation the lines arrive prefilled and are kept or edited — the first two
  // routes, indistinguishable here on purpose — and a free entry types them.
  // Company and rep are DERIVED from the thread `[18 §7]` and the form does not
  // offer them; a free entry names a company, and names a rep only when a
  // `can_dispatch` holder is raising one for somebody else `S108`.
  const quotationThreadId = fields.uuid("quotationThreadId");
  const isFreeEntry = !quotationThreadId;

  const companyId = isFreeEntry
    ? fields.uuid("companyId", { required: true })
    : null;
  const userId = isFreeEntry ? fields.uuid("userId") : null;
  // `S74` — shape only. Whether it is required, ignored or refused depends on
  // the quotation's own project, which only the data layer can read.
  const projectId = isFreeEntry ? null : fields.uuid("projectId");
  const dispatchDate = fields.date("dispatchDate", { required: true });

  const shipment = readShipment(fields);

  const lines = readLines(formData, fields);
  if (!fields.ok || !dispatchDate || !shipment.stock || !shipment.shipment) {
    return fields.state;
  }

  let dispatchId: string;
  try {
    const dispatch = await requestDispatch(session, {
      lines,
      dispatchDate,
      quotationThreadId,
      companyId,
      userId,
      projectId,
      stock: shipment.stock,
      shipment: shipment.shipment,
      cargoDestination: shipment.cargoDestination,
    });
    dispatchId = dispatch.id;
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }

  const locale = await getLocale();
  revalidatePath("/dispatches");
  redirect({ href: `/dispatches/${dispatchId}`, locale });
  throw new Error("unreachable"); // redirect() never returns
}

/**
 * **Edit a request** `S125` `S62` — the rep's while it is a draft, the
 * coordinator's once it is submitted. Which of the two is asking is the data
 * layer's question, not this one's.
 */
export async function updateDispatchRequestAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);

  const projectId = fields.uuid("projectId");
  const dispatchDate = fields.date("dispatchDate", { required: true });
  const shipment = readShipment(fields);
  const lines = readLines(formData, fields);
  if (!fields.ok || !dispatchDate || !shipment.stock || !shipment.shipment) {
    return fields.state;
  }

  try {
    await updateDispatchRequest(session, id, {
      lines,
      dispatchDate,
      projectId,
      stock: shipment.stock,
      shipment: shipment.shipment,
      cargoDestination: shipment.cargoDestination,
    });
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }

  const locale = await getLocale();
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  redirect({ href: `/dispatches/${id}`, locale });
  throw new Error("unreachable"); // redirect() never returns
}

/** **The rep hands it over** `S72`. */
export async function submitDispatchRequestAction(
  id: string,
): Promise<FormState> {
  const session = await requireSession();
  try {
    await submitDispatchRequest(session, id);
  } catch (error) {
    return ruleErrorState(error);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}

/**
 * **The coordinator approves** `S72` — the one event that credits a target, and
 * the one that fires `S74`'s write-back. Four screens go stale at once.
 *
 * **It carries the payment method** `S70` `S73`, which is why this stopped
 * being a field-less bound-id act. *A dispatch cannot be approved without a
 * payment method*, and putting the choice on the approval itself is what makes
 * that unbreakable rather than merely checked: there is no path to `approved`
 * that does not pass through this form. The rep never sees the field — `S70`
 * puts it in the coordinator's head, *because she is the one who confirms it
 * with finance*.
 */
export async function approveDispatchRequestAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);
  const method = fields.option("paymentMethod", PAYMENT_METHODS, {
    required: true,
  });
  // `S71` — *an optional note carries anything the list does not*.
  const note = fields.text("paymentNote", { max: 500 });
  if (!fields.ok || !method) return fields.state;

  try {
    await approveDispatchRequest(session, id, { method, note });
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  // Approval is what credits `S72`, so the achievement figures are stale.
  revalidatePath("/targets");
  // `S74` — approving can write a project onto a quotation and add a
  // participant to that project, so both of those screens are stale too.
  revalidatePath("/quotations");
  revalidatePath("/projects");
  return {};
}

/** **The coordinator refuses**, with a reason `S124`, which archives it `S122`. */
export async function refuseDispatchRequestAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);
  const reason = fields.text("reason", {
    required: true,
    max: COMMENT_BODY_MAX,
  });
  if (!fields.ok || !reason) return fields.state;

  try {
    await refuseDispatchRequest(session, id, reason);
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}

/** **Only the coordinator may revive one** `S122`, and it returns to the rep. */
export async function reviveDispatchRequestAction(
  id: string,
): Promise<FormState> {
  const session = await requireSession();
  try {
    await reviveDispatchRequest(session, id);
  } catch (error) {
    return ruleErrorState(error);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}

/**
 * **The SMAC dispatch number** `S121` — written after approval, by the
 * coordinator, when SMAC issues it.
 *
 * A seventh act rather than a field on the approval, because the rule is
 * explicit that *it is not a condition of approval*. Nothing but `/dispatches`
 * and this record is revalidated: a number moves no square metres, credits
 * nothing and changes no figure `S72`.
 */
export async function setDispatchSmacNumberAction(
  id: string,
  _previous: FormState,
  formData: FormData,
): Promise<FormState> {
  const session = await requireSession();
  const fields = readFields(formData);
  // `S5` — a human types it, so FACET assumes it can be wrong. No format is
  // checked: SMAC owns the format and there is no integration to ask.
  const number = fields.text("smacDispatchNumber", {
    required: true,
    max: 100,
  });
  if (!fields.ok || !number) return fields.state;

  try {
    await setDispatchSmacNumber(session, id, number);
  } catch (error) {
    return ruleErrorState(error, fields.values);
  }
  revalidatePath("/dispatches");
  revalidatePath(`/dispatches/${id}`);
  return {};
}
